uhmanoalink/manoa-link

README.md

Updated README to include:
- App description
- Installation instructions
- License note
No testing necessary.

26 update readme

---

config/settings.development.json

deploy for final project

---

.github/workflows/deploy.yml

- Fixes deployment workflow by installing Meteor
No additional context

add install meteor

---

app/imports/startup/server/Accounts.js
app/imports/ui/components/NavBar.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/layouts/CompanyProtectedRoute.jsx
app/imports/ui/layouts/StudentProtectedRoute.jsx
app/imports/ui/layouts/UserProtectedRoute.jsx
app/package-lock.json
app/tests/addevents.page.ts
app/tests/companylisting.page.ts
app/tests/listevents.page.ts
app/tests/myprofile.page.ts
app/tests/signin.page.ts
app/tests/signout.page.ts
app/tests/signup.page.ts
app/tests/tests.testcafe.ts
config/settings.development.json

- Note: Did not write any tests for this.
- Added CompanyProtectedRoute and UserProtectedRoute to separate what company sees and what user sees
- Admin has access to both of these routes
- Added default account 'company@foo.com' with same default password
- Modified NavBar, just for the MyProfile page

Added Protected Routes

---

app/imports/startup/server/Accounts.js
app/imports/ui/components/NavBar.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/layouts/CompanyProtectedRoute.jsx
app/imports/ui/layouts/UserProtectedRoute.jsx
app/package-lock.json
app/tests/addevents.page.ts
app/tests/companylisting.page.ts
app/tests/listevents.page.ts
app/tests/myprofile.page.ts
app/tests/signin.page.ts
app/tests/signout.page.ts
app/tests/signup.page.ts
app/tests/tests.testcafe.ts
config/settings.development.json

Company Listing Page Mockup

---

.github/workflows/deploy.yml

- Change back to global mup installation
**Keep branch**

fix-deployment-workflow - back to global mup install

---

.github/workflows/deploy.yml

- Builds the project before deploying it
- Compiles Sass files

Add build step to deployment

---

.github/workflows/deploy.yml
.github/workflows/testcafe.yml
app/package.json

- Added a build script for semanticity (instead of build step in workflow running prestart)
- Build step also runs `meteor reset`
- Updated workflow actions to latest

add build script and update workflows

---

app/imports/api/company/Company.js
app/imports/api/event/Event.js
app/imports/api/position/Position.js
app/imports/ui/components/Company.jsx
app/imports/ui/components/Event.jsx
app/imports/ui/components/Position.jsx
app/imports/ui/components/User.jsx

Components for company, event, position, and user
If you don't need user component, don't have to use.

24 make components files for studnet company event position

---

app/client/scss/components/__components.scss
app/client/scss/components/_event-card.scss
app/imports/api/event/Event.js
app/imports/startup/server/Mongo.js
app/imports/ui/components/Event.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/AddEvent.jsx
app/imports/ui/pages/EditEvent.jsx
app/imports/ui/pages/ListEvents.jsx
app/package-lock.json
app/package.json
config/settings.development.json

Implement list-events, add-event, edit-event
Change event api, event component.
For event component, I tried to treat data only in the submit function, but schema needed defaultValue setting for the value that can't be set in the web request.
Use npm install react-select 
to make multiple select with search and implement connection for multi tags checked. 
For edit-event,
just let you know that
useEffect(() => {
});
is for getting the tags in real time that has been selected before you edited.
I will add the 'multiple select filter with search' on the list events or the event page that we are going to make later, when we finish design of the page.

74 implement list-events, add-event, edit-event

---

app/client/main.js
app/imports/startup/both/Methods.js
app/imports/ui/pages/SignUp.jsx
app/server/main.js
app/tests/navbar.component.ts
app/tests/signup.page.ts
app/tests/tests.testcafe.ts
app/tests/types/RoleType.ts

Since `Roles.createRole()` directly updates the database, Meteor only allows the server to call it. This obviously causes a problem that the role is not found when trying to call `Roles.addUsersToRoles()` because 1) the role does not exist locally (you can check MiniMongo in the Chrome DevTools) and 2) it doesn't have access to the full database of roles.
Add a meteor method called 'initUser' and update the roles of the new user there.
New Meteor Methods:
Initializes new users by adding them to the given role.
```js
'initUser'({ userId, role }) {
Roles.createRole(role, { unlessExists: true });
Roles.addUsersToRoles(userId, [role]);
},
```
- `userId` (string) - The ID of the new user
- `role` (string) - The …

99 fix registration roles

---

app/imports/ui/components/Footer.jsx
app/tests/footer.component.ts

- Linked footer links to home, about us, and faq pages in project page
- "Blog" could go to another page if we make a dedicated blog, but I think our project page is basically a blog anyway

82 link the about us blog and faq page in footer

---

app/client/scss/components/_event-card.scss
app/client/scss/pages/__pages.scss
app/client/scss/pages/_admin-dashboard.scss
app/imports/ui/components/CompanyAdmin.jsx
app/imports/ui/components/DeleteConfirmation.jsx
app/imports/ui/components/Event.jsx
app/imports/ui/components/EventAdmin.jsx
app/imports/ui/components/PositionAdmin.jsx
app/imports/ui/components/UserAdmin.jsx
app/imports/ui/pages/AdminDashboard.jsx
app/imports/ui/pages/Dashboard.jsx
app/tests/admindashboard.page.ts
app/tests/tests.testcafe.ts

- Admin versions of the cards for Student (still called User here), Company, Event, Listing (called Position) have buttons to delete
- Changed event card CSS from affecting all cards to only event cards, fixing scaling, and removing useless lines
- See all students, companies, events, and listings
- Can edit and delete those documents directly from the database
- Responsive layout at smaller viewports
Clicking delete opens a confirmation modal. Control-clicking the delete button ignores the modal.
Renders as a Button:
```jsx
<Button onClick={handleShowConfirm} variant="danger" size="sm">Delete</Button>
```
and shows a modal when clicked:
- `collection` (`Mongo.Collection<Document, Document>`): The …

107 make admin dashboard

---

app/client/scss/globals/_colors.scss
app/client/scss/globals/_utilities.scss
app/client/scss/pages/_my-profile.scss
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/CompanyProfile.jsx
app/imports/ui/pages/Profile.jsx
app/imports/ui/pages/StudentProfile.jsx
app/tests/companyprofile.page.ts
app/tests/studentprofile.page.ts
app/tests/tests.testcafe.ts

- Created very basic company profile page
- Company name
- Description
- Company website
- Address
- Image
- Created linking `Profile` page, similar to the `Dashboard` page
Tests only make sure the pages are visible.

112 create company profile page

---

app/client/scss/globals/_typography.scss

Fixed font

---

app/imports/startup/both/Methods.js
app/imports/ui/pages/SignUp.jsx

- Cleaned up meteor method syntax
- Checking inputs
- No issue, was a small change.
- Tested manually

clean up methods

---

app/imports/api/event/Event.js
app/imports/api/listing/Listing.js
app/imports/ui/pages/MainEventsList.jsx

- Fixed student publication usage for students
- Fixed id's for the sections, they were on each card (which should never happen) and not on the section itself
None

131 fix failing events page tests

---

app/imports/api/image/Image.js
app/lib/files.js

- `url { string }` - The image should be obtained from a GET request to this URL (you can check this with something like [Postman](https://www.postman.com/) but in most cases this will already be true, assuming you can paste the URL in your browser and it displays just the image).
- `fileName { string }` - An optional file name (with extension). E.g. 'my-new-image.png'
Example Usage:
The most important things to note are:
> 1) Make sure you are subscribed to the Images publication.
> 2) All the methods are asynchronous, meaning you have to handle the Promised return values with `.then` or use `async`/`await` like in the example code.
> 3) All `find`s and `findOne`s should be done in a `useTracker` hook.
> …

add more helper functions for images

---

app/imports/api/image/Image.js
app/imports/startup/server/Publications.js
app/imports/ui/components/EventCompany.jsx
app/imports/ui/components/FileUpload.jsx
app/imports/ui/pages/AddEvent.jsx
app/imports/ui/pages/CompanyManageEvents.jsx
app/imports/ui/pages/EditEvent.jsx
app/imports/ui/pages/EventPage.jsx

FIX Image Uploading by lazy rendering image after everything done
Add image uploading to add-page, edit-event page.
Add the image to the page view.
Fix some error for event page.
- If I go to edit page, all the data from mongo is gone without no reason, that's why auto form couldn't take the default event data. If anyone can resolve this, it would be thank you.
- [] I have added tests that prove my fix is effective or that my feature works

Fixing event company image uploading - add this function to all the page, and fix errors related to it

---

app/imports/startup/server/Publications.js
app/imports/ui/pages/AddEvent.jsx
app/imports/ui/pages/CompanyManageEvents.jsx
app/tests/signup.page.ts

- Fixed company publications
- Fixed add event
- The company id field was incorrectly being filled out with Meteor.userId() instead of the id of the company
- Updated manage events subscriptions to match the new publications

fix add events

---

app/client/scss/pages/_my-profile.scss
app/imports/startup/both/Methods.js
app/imports/ui/pages/StudentProfile.jsx
app/lib/files.js

Added fields to change student profile information
- Name
- Profile picture
- Email
- Password

154 add profile editing for students

---

app/imports/ui/components/NavBar.jsx

- Navbar image now correctly shows the user's profile image

168 fix navbar profile picture

---

app/imports/ui/pages/StudentDashboard.jsx

Fixed www error

---

app/client/scss/pages/_my-profile.scss
app/imports/ui/pages/CompanyProfile.jsx
app/imports/ui/pages/StudentProfile.jsx

- Added company profile page
- Shows the company's information and lets them change it
- Can also change account details

170 make company profile page

---

app/imports/ui/pages/CompanyDashboard.jsx

Fix undefined

---

app/imports/ui/components/Listing.jsx
app/imports/ui/components/PastEvent.jsx
app/imports/ui/pages/MainEventsList.jsx
app/imports/ui/pages/ManageListings.jsx
app/imports/ui/pages/StudentDashboard.jsx

- Fixed problems 1,7,8 as posted on discord, and repasted below:
- In saved jobs, the company ID is shown instead of company name
- Past events not updated yet
- Make images show up on saved jobs

Beyond M3: Small style fixes
